import MainLayout from "@/components/layout/MainLayout";
import "./globals.css";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
  verification: {
    google: "ti7mssPi4rX4EGAMcoQM8uhMRKK4EQfxfk_tkFYeyw0",
  },
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="jp">
      <body>
        <MainLayout>{children}</MainLayout>
      </body>
    </html>
  );
}
